### ISSUE TITLE
Error on Orchid 10.x

### ISSUE THREAD

**Issue by Kostyavas** [orchidcommunity/TinyMCE#4]
Orchid Platform v 10.5.0
Laravel 8

There are error while using TinyMCE with Orchid v.10

window.platform was removed from app.js
https://github.com/orchidsoftware/platform/commit/692ca5287b3f55b077358a38c2bb6295b8fd0ffc#diff-583a1f586bc298813341bce6fec77a1f6338f2559471fe600f15a18316fe82bd

![error](https://user-images.githubusercontent.com/29770920/121706261-20656b00-cade-11eb-95d9-39d0e085c0dd.png)

#3

**Comment by tabuna** [comment]
Hi @Kostyavas, I have no plans to develop this package (TinyMCE). 
If you have a desire to continue it, then I can assign you to be in charge and give access to this repo

**Comment by Kostyavas** [comment]
@tabuna 
OK. I'm ready to support this package in the near future

**Comment by Kostyavas** [comment]
pull request #3 merged
