### ISSUE TITLE
`o.prefix` is not a function

### ISSUE THREAD

**Issue by mahmoudmohamedramadan** [orchidcommunity/TinyMCE#7]
This is a very awesome tool BUT, there is an issue when I uploaded an image the message of `o.prefix is not a function` appeared to me. How I can solve this issue?

**Comment by mahmoudmohamedramadan** [comment]
@tabuna Hey sir, any solutions for this issue?

**Comment by tabuna** [comment]
I am not the maintainer of this package. All repositories located here are transferred to the support of the community.
If you want to become a supporter, then write to me.

**Comment by Kostyavas** [comment]
@mahmoudmohamedramadan 

Fixed in new release
